import Head from "next/head";
import { motion } from "framer-motion";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Edmira</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id={styles.container}>

        <div id={styles.mobile}>
          <article>
            <img src="/icon-close.svg" id={styles.close} />
            <section>
              <Link href="/">Home</Link>
              <Link href="#about">About</Link>
              <Link href="/">Forum</Link>
              <Link href="/">News Feed</Link>
              <Link href="/">My Courses</Link>
            </section>

            <aside>
              <button id="sign">Sign up</button>
              <button>Login</button>
            </aside>
          </article>
          
        </div>

        {/* Header section */}

        <motion.header id={styles.header}
          initial={{y:-100, opacity:0}}
          whileInView={{y:0, opacity:1}}
          transition={{duration:2}}
        >
          <section>
            <img src="/Logo1.jpg"/>
          </section>

          <section>
            <Link href="/">Home</Link>
            <Link href="#about">About</Link>
            <Link href="/">Forum</Link>
            <Link href="/">News Feed</Link>
            <Link href="/">My Courses</Link>
          </section>

          <aside>
            <button id="sign">Sign up</button>
            <button>Login</button>
            <img src="/icon-hamburger.svg" id={styles.hamburger} />
          </aside>

        </motion.header>

        {/* Hero section */}

        <div id={styles.heroSection}>
          <section>
            <motion.h1
              initial={{x:100, opacity:0}}
              whileInView={{x:0, opacity:1}}
              transition={{duration:2}}
            >Revolution Medical <span>Education in Africa</span></motion.h1>
            <motion.span
              initial={{x:-100, opacity:0}}
              whileInView={{x:0, opacity:1}}
              transition={{duration:2, delay:0.2}}
            >Learn smarter. Prepare better. Succeed faster.</motion.span>
            <motion.p
              initial={{y:100, opacity:0}}
              whileInView={{y:0, opacity:1}}
              transition={{duration:2, delay:1}}
            >Edmira is a mobile app for Nigerian medical students packed with curriculum-aligned tools like quizzes, animations, practice banks, and AI-powered study support. Everything you need to bridge the gap between theory and practice - all in one place.</motion.p>
            <nav>
              <motion.button
                initial={{x:-100, opacity:0}}
                whileInView={{x:0, opacity:1}}
                transition={{duration:2, delay:0.2}}
              >Get Started</motion.button>
              <motion.button
                initial={{x:100, opacity:0}}
              whileInView={{x:0, opacity:1}}
              transition={{duration:1, delay:0.2, type: "spring", stiffness: 120}}
              >Downalod App</motion.button>
            </nav>
          </section>
          <section>
            <motion.img src="/illustration.jpg" 
              initial={{scale:0, opacity:0}}
              whileInView={{scale:1, opacity:1}}
              transition={{duration:2, delay:0.2}}
            />
          </section>
        </div>

        {/* About section */}

        <div id={styles.about}>
          <motion.h1
              initial={{y:-100, opacity:0}}
              whileInView={{y:0, opacity:1}}
              transition={{duration:2, delay:0.2}}
          >Who We Are</motion.h1>
          <motion.section
            initial={{x:300, opacity:0}}
            whileInView={{x:0, opacity:1}}
            transition={{duration:2, delay:0.2}}
          >
            <h2>About Us</h2>
            <p> Edmira is a mobile learning app designed for medical students in Nigerian universities. Our goal is to provide curriculum-aligned, accessible, and interactive study tools that help students: - Study smarter and more efficiently. - Prepare better for exams and practicals. - Bridge the gap between theory and clinical practice. We believe medical students deserve more than textbooks and lecture notes they need digital tools, quizzes, practice banks, animations, and AI-powered study support that make learning easier and engaging.</p>
          </motion.section>
          <aside>
            <motion.nav
              initial={{x:-300, opacity:0}}
              whileInView={{x:0, opacity:1}}
              transition={{duration:2, delay:0.2}}
            >
              <h2>Our Vision</h2>
              <p>To become the leading edtech platform for medical education in Africa, empowering students with digital learning resources that improve knowledge retention, exam performance, and real-world medical practice.</p>
            </motion.nav>
          </aside>
        </div>
      </div>
    </>
  );
}
